### ISSUE TITLE
Error: "An error occurred while establishing a connection with SQL Server"

### ISSUE THREAD

**Issue by it19862** [rafatdin/gantt#1]
I downloaded your application to a local computer.
I did not set up a connection to the `Sql server`
I launched the application.
Everything worked.
I created a resource, created tasks, looked at the Gantt chart.

I try to run the application again, get an error.

System.Data.SqlClient.SqlException:
"An error occurred while establishing a connection with SQL Server
connected to a network or to a specific instance.
Server not found or unavailable.
Make sure the instance name is correct and
that remote connections are allowed on SQL Server.
(provider: TCP Provider,
error: 0 - The remote computer rejected this network connection.) "

**Question.**
How to fix the error?

![2019-07-28_18-21-40](https://user-images.githubusercontent.com/18245828/62009429-cb2d4400-b167-11e9-8c89-ab32e60f35f5.png)

**Comment by rafatdin** [comment]
> Make sure the instance name is correct and
that remote connections are allowed on SQL Server. (provider: TCP Provider,
> error: 0 - The remote computer rejected this network connection.)

It clearly says that your DB is refusing the connection. You need to set up the connection properly.

**Comment by it19862** [comment]
@rafatdin 
Launched MSSql.
Everything is working.
